# Not using ghpages plugin we use the same versions required for compatibility
# see https://pages.github.com/versions/

image: ruby:2.7.1

variables:
  JEKYLL_ENV: production

pages:
  script:
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
