name: Deploy site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Build (For forks)
        if: ${{ $github.repository_owner != 'lite-xl' }}
        run: |
          bundle exec jekyll build \
            --destination public/  \
            --baseurl "/$(echo '${{ github.repository }}' | cut -d/ -f2)"
      - name: Build (for lite-xl org)
        if: ${{ $github.repository_owner == 'lite-xl' }}
        run: bundle exec jekyll build --destination public/
      - name: Upload to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
